export const COMPONENT_REACT = "PricingReact";
export const COMPONENT_HTML = "PricingHtml";

export const PRODUCT_TYPES = ["component", "template"];

export const COMPONENT_LIST = [
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgsample1.png",
    hoverText: "This element displays several cost comparison.",
    title: "Pricing Sections",
    subTitle: "Pricing component",
    type: "pricing",
    date: "2023-05-01",
    tipForUse: "",
    tailwindVersion: "",
    slug: "sample-1",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react", "HTML"],
    pageDetails: {
      componentReact: "PricingReact",
      componentHTML: "PricingHtml",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgsample2.png",
    hoverText: "On hover, the icons in this pricing component will change.",
    title: "Comparing Prices",
    subTitle: "Pricing component",
    type: "pricing",
    date: "2023-08-23",
    tipForUse: "",
    tailwindVersion: "",
    slug: "sample-2",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "PricingReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgsample3.png",
    hoverText: "This price includes wonderful distribution with promotion.",
    title: "Promotional Pricing",
    subTitle: "Pricing component",
    type: "pricing",
    date: "2022-03-20",
    tipForUse: "",
    tailwindVersion: "",
    slug: "sample-3",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react", "HTML"],
    pageDetails: {
      componentReact: "PricingReact",
      componentHTML: "PricingHtml",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgsample4.png",
    hoverText: "This pricing component includes a free trial period.",
    title: "Pricing Plans",
    subTitle: "Pricing component",
    type: "pricing",
    date: "2023-03-20",
    tipForUse: "",
    tailwindVersion: "",
    slug: "sample-4",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react", "HTML"],
    pageDetails: {
      componentReact: "PricingReact",
      componentHTML: "PricingHtml",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgsample5.png",
    hoverText:
      "The distribution of three pricing comparison is shown here in table style.",
    title: "Pricing Table",
    subTitle: "Pricing component",
    type: "pricing",
    date: "2023-01-22",
    tipForUse: "",
    tailwindVersion: "",
    slug: "sample-5",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "PricingReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcreditcard1.png",
    hoverText: "Component for credit cards that has dynamic colors and fields.",
    title: "Dynamic card",
    subTitle: "Creditcard component",
    type: "creditcard",
    date: "2023-01-01",
    tipForUse: "",
    tailwindVersion: "",
    slug: "card-1",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "CreditcardReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcreditcard2.png",
    hoverText:
      "Beautiful graphic backdrop and field validation on the ATM card.",
    title: "Credit Card",
    subTitle: "Creditcard component",
    type: "creditcard",
    date: "2022-11-03",
    tipForUse: "",
    tailwindVersion: "",
    slug: "card-2",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "CreditcardReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcreditcard3.png",
    hoverText: "ATM card with gorgeous graphic backdrop and field validation.",
    title: "Credit Card",
    subTitle: "Creditcard component",
    type: "creditcard",
    date: "2023-03-01",
    tipForUse: "",
    tailwindVersion: "",
    slug: "card-3",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "CreditcardReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcarousal1.png",
    hoverText: "Responsive and simple carousel with arrows.",
    title: "Carousel with controls",
    subTitle: "Carousel component",
    type: "carousel",
    date: "2022-07-01",
    tipForUse: "",
    tailwindVersion: "",
    slug: "carousel-1",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "CarouselReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcarousal2.png",
    hoverText:
      "Carousel component with an infinite loop, dynamic text, and with fade animation",
    title: "All-inclusive carousel",
    subTitle: "Carousel component",
    type: "carousel",
    date: "2023-03-20",
    tipForUse: "",
    tailwindVersion: "",
    slug: "carousel-2",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "CarouselReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bg-cards.png",
    hoverText: "Attractive, functional, and effective card Layout.",
    title: "cards with scale effect",
    subTitle: "Card component",
    type: "card",
    date: "2023-03-01",
    tipForUse: "",
    tailwindVersion: "",
    slug: "profilecard",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "CardReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/animation.gif",
    hoverText: "Component for the loader, button, and design with animation.",
    title: "Infinite Animation",
    subTitle: "Animation component",
    type: "animation",
    date: "2023-03-14",
    tipForUse: "",
    tailwindVersion: "",
    slug: "animation-infinite",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "AnimationReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bg-btn-1.png",
    hoverText: "Flexible color and style buttons.",
    title: "categories of buttons",
    subTitle: "Button component",
    type: "button",
    date: "2023-03-16",
    tipForUse: "",
    tailwindVersion: "",
    slug: "sample1",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "ButtonSampleReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bg-btn-2.png",
    hoverText:
      "Colorful buttons component with an outline,rounded and fill style.",
    title: "Fill and Round Buttons",
    subTitle: "Button component",
    type: "button",
    date: "2023-03-20",
    tipForUse: "",
    tailwindVersion: "",
    slug: "sample2",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "ButtonSampleReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bganimatedbutton.gif",
    hoverText: "Components of buttons with different hover effects.",
    title: "3D Buttons",
    subTitle: "Button component",
    type: "button",
    date: "2023-03-13",
    tipForUse: "",
    tailwindVersion: "",
    slug: "sample3",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "ButtonSampleReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bginput.jpg",
    hoverText: "Various input field types with dynamic border colors.",
    title: "various inputs",
    subTitle: "Input component",
    type: "input",
    date: "2023-03-26",
    tipForUse: "",
    tailwindVersion: "",
    slug: "input-sample-1",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "InputReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgradiobutton.jpg",
    hoverText: "Radio button with a unique style.",
    title: "Radio Buttons.",
    subTitle: "Radio Button Component",
    type: "radiobutton",
    date: "2023-03-27",
    tipForUse: "",
    tailwindVersion: "",
    slug: "radiobutton-sample-1",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "RadioButtonReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcheckbox.png",
    hoverText: "Checkbox elements with vibrant and stylish categories.",
    title: "Checkbox Variations",
    subTitle: "Checkbox component",
    type: "checkbox",
    date: "2023-03-28",
    tipForUse: "",
    tailwindVersion: "",
    slug: "checkbox-sample-1",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "CheckboxReact",
    },
  },

  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgadvertise.png",
    hoverText: "Spotlight components that highlight important points.",
    title: "Spotlight card",
    subTitle: "Card component",
    type: "card",
    date: "2023-04-06",
    tipForUse: "",
    tailwindVersion: "",
    slug: "spotlight",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react", "HTML"],
    pageDetails: {
      componentReact: "CardReact",
      componentHTML: "CardHtml",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcountdown1.png",
    hoverText: "Timer component to show the user how much time has to wait.",
    title: "Day Countdown",
    subTitle: "Timer component",
    type: "timer",
    date: "2023-04-07",
    tipForUse: "",
    tailwindVersion: "",
    slug: "timer-1",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "TimerReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcountdown2.png",
    hoverText:
      "A responsive timer that displays the conclusion of our waiting time.",
    title: "Box Countdown",
    subTitle: "Timer component",
    type: "timer",
    date: "2023-04-10",
    tipForUse: "",
    tailwindVersion: "",
    slug: "timer-2",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "TimerReact",
    },
  },

  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcountdown3.png",
    hoverText:
      "Timer component which used to display remaining time for a particular function.",
    title: "Countdown Labels",
    subTitle: "Timer component",
    type: "timer",
    date: "2023-04-01",
    tipForUse: "",
    tailwindVersion: "",
    slug: "timer-3",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "TimerReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcountdown4.png",
    hoverText:
      "A responsive timer that displays the conclusion of our waiting time.",
    title: "Live Countdown",
    subTitle: "Timer component",
    type: "timer",
    date: "2023-04-05",
    tipForUse: "",
    tailwindVersion: "",
    slug: "timer-4",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "TimerReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcountdown5.png",
    hoverText:
      "Timer component which used to display remaining time for a particular function.",
    title: "Circle Countdown",
    subTitle: "Timer component",
    type: "timer",
    date: "2023-04-09",
    tipForUse: "",
    tailwindVersion: "",
    slug: "timer-5",
    isCustomizeColor: false,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "TimerReact",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcountdown5.png",
    hoverText: "Footer",
    title: "Footer Componnet",
    subTitle: "Footer component",
    type: "footer",
    date: "2023-05-04",
    tipForUse: "",
    tailwindVersion: "",
    slug: "example-1",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react", "HTML"],
    pageDetails: {
      componentReact: "FooterReact",
      componentHTML: "FooterHtml",
    },
  },
  {
    section: "component",
    mainImageSrc: "/bgcomponents/bgcountdown5.png",
    hoverText:
      "Timer component which used to display remaining time for a particular function.",
    title: "Header",
    subTitle: "Header component",
    type: "header",
    date: "2023-04-09",
    tipForUse: "",
    tailwindVersion: "",
    slug: "header-1",
    isCustomizeColor: true,
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: "TimerReact",
    },
  },
];
