export const TEMPLATE_REACT = "templateReact";

export const TemplateConstant = [
  {
    section: "template",
    mainImageSrc: "/bgcomponents/bgcrypto.png",
    hoverText: "This is Landing Page Template",
    title: "Crypto",
    subTitle: "Landing Page 2",
    type: "crypto",
    tipForUse: "",
    tailwindVersion: "",
    date: "2023-01-09",
    slug: "temp2",
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: TEMPLATE_REACT,
    },
  },
  {
    section: "template",
    mainImageSrc: "/bgcomponents/bgnft.png",
    hoverText:
      "Responsive landing page template with cards, category and infinite carousal.",
    title: "3DNFT",
    subTitle: "Landing Page 1",
    type: "3dnft",
    tipForUse: "",
    tailwindVersion: "",
    date: "2023-03-11",
    slug: "temp1",
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: TEMPLATE_REACT,
    },
  },
  {
    section: "template",
    mainImageSrc: "/bgcomponents/bgadvocate.png",
    hoverText: "Landing page template with all primary requirements.",
    title: "Advocate",
    subTitle: "Landing Page 3",
    type: "advocate",
    tipForUse: "",
    tailwindVersion: "",
    date: "2023-01-01",
    slug: "temp3",
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: TEMPLATE_REACT,
    },
  },
  {
    section: "template",
    mainImageSrc: "/bgcomponents/bgtbdesign.png",
    hoverText: "This is landing page template for showing person's portfolio",
    title: "TBDesign",
    subTitle: "Landing Page 4",
    type: "tbdesign",
    tipForUse: "",
    tailwindVersion: "",
    date: "2023-02-01",
    slug: "temp4",
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: TEMPLATE_REACT,
    },
  },
  {
    section: "template",
    mainImageSrc: "/bgcomponents/bgdreamagency.png",
    hoverText: "This is Landing Page Template",
    title: "Dream Agency",
    subTitle: "Landing Page 5",
    type: "dreamagency",
    tipForUse: "",
    tailwindVersion: "",
    date: "2023-03-15",
    slug: "temp5",
    codeAvailableLanguages: ["react"],
    pageDetails: {
      componentReact: TEMPLATE_REACT,
    },
  },
];
